close all;
clear all;
clc;
hf=figure(...
    'Units','Normalized',...
    'Menu','none',...
    'Color','w',...
    'Position',[0.1 0.1 0.7 0.5]);

ha=axes(...
    'Parent',hf,...
    'Units','Normalized',...
    'Position',[0.1 0.1 0.6 0.8]);

hb1=uicontrol(...
    'Style','pushbutton',...
    'Callback','try,delete(allchild(ha));end',...
    'String','clear',...
    'Units','Normalized',...
    'Position',[0.8 0.2 0.15 0.15]);

hb2=uicontrol(...
    'Style','pushbutton',...
    'Callback','plot(sin([0:0.01:10]));',...
    'String','sin',...
    'Units','Normalized',...
    'Position',[0.8 0.6 0.15 0.15]);

hb3=uicontrol(...
    'Style','pushbutton',...
    'Callback','plot(cos([0:0.01:10]));',...
    'String','cos',...
    'Units','Normalized',...
    'Position',[0.8 0.4 0.15 0.15]);


